const ChiSoThaiDo = {
    1: 'Chỉ số thái độ của bạn là: 1\n' +
        'Chỉ số thái độ 1 tượng trưng cho một cá tính độc lập, tự tin và kín đáo, luôn toát lên sự mạnh mẽ từ bên trong. Người mang chỉ số này thường có xu hướng tự tin vào khả năng của mình, coi trọng bản thân và không dễ gì nhờ vả ai. Sự tự tin là một yếu tố cốt lõi giúp họ khẳng định khả năng lãnh đạo và quyết định mọi thứ một cách dứt khoát, không để người khác tác động đến con đường họ chọn. Họ cảm nhận sâu sắc giá trị của sự tự lập, chính điều này giúp họ luôn cảm thấy tự tin khi đối mặt với những thử thách. Chỉ số thái độ 1 còn cho thấy một năng lượng tích cực lan tỏa, luôn sẵn sàng chủ động tiếp cận mọi vấn đề với tâm thế “sẵn sàng chinh phục".\n' +
        'Thế nhưng, với tính cách mạnh mẽ và cái tôi lớn, những người mang chỉ số này đôi khi bị hiểu lầm là kiêu ngạo hoặc tự mãn. Họ thích nhận được sự yêu mến và tôn trọng từ những người xung quanh; khi nhận được sự tin tưởng, năng lượng của họ lại càng thêm mạnh mẽ, giúp họ dễ dàng đạt được những mục tiêu đã đề ra. Điều này khiến họ trở nên bền bỉ, kiên định, không dễ dàng bị khuất phục trước khó khăn. Tuy nhiên, đôi khi chính sự tự tin này có thể khiến họ trở thành người quá tự cao, xem mình là trung tâm và không lắng nghe ý kiến của người khác. Để giữ được mối quan hệ lâu dài và hòa hợp, số 1 nên học cách khiêm tốn, hiểu rằng sự thành công không chỉ đến từ cá nhân mà còn từ sự hỗ trợ của những người xung quanh, đặc biệt là trong các mối quan hệ gia đình và tình cảm.\n' +
        'Sức mạnh ý chí là điểm sáng của chỉ số thái độ 1, giúp họ đối mặt với mọi thử thách. Khả năng này khiến họ không ngừng nỗ lực, thậm chí có thể vượt qua những giới hạn mà người khác cho là không thể. Song, một lời khuyên cho những người có chỉ số thái độ 1 là nên kiềm chế cái tôi quá lớn, đồng thời học cách khiêm tốn, hiểu rằng sự bền vững trong cuộc sống còn đến từ việc biết lắng nghe và đồng cảm với người khác.\n',
    2: 'Chỉ số thái độ của bạn là: 2\n' +
        'Chỉ số thái độ 2 đại diện cho những con người nhẹ nhàng, tinh tế và có khả năng quan sát xuất sắc. Số 2 không chỉ là người biết lắng nghe mà còn có thể hiểu thấu suy nghĩ và cảm xúc của những người xung quanh. Khả năng quan sát tuyệt vời khiến họ như có một giác quan thứ sáu, dễ dàng nắm bắt được tâm tư của người đối diện mà không cần người khác phải nói ra. Điều này khiến họ trở nên vô cùng gần gũi và thân thiện, tạo cảm giác an toàn cho người xung quanh. Họ không chỉ lắng nghe bằng tai mà còn bằng cả trái tim, nhờ đó mà có thể xây dựng được những mối quan hệ gắn kết và sâu sắc.\n' +
        'Người mang chỉ số thái độ 2 rất nhạy cảm và dễ xúc động. Họ luôn ưu tiên hạnh phúc của người khác, luôn sẵn lòng giúp đỡ và hy sinh vì những người thân yêu. Tuy nhiên, vì quá quan tâm đến cảm xúc của người khác, số 2 có thể trở nên lo lắng khi cố gắng quản lý hoặc điều chỉnh cảm xúc của mình để không làm mất lòng người khác. Lời khuyên cho họ là nên giữ cân bằng, đừng để bản thân quá đắm chìm vào việc làm hài lòng người khác mà quên đi những nhu cầu cá nhân. Với sự quan tâm chân thành và lòng trắc ẩn sâu sắc, số thái độ 2 thường có những mối quan hệ tuyệt vời, được mọi người yêu mến và ngưỡng mộ bởi sự đồng cảm và lòng tốt hiếm có.\n',
    3: 'Chỉ số thái độ của bạn là: 3\n' +
        'Người có chỉ số thái độ 3 mang trong mình sự năng động, sáng tạo và vui vẻ, luôn tràn đầy năng lượng tích cực và khả năng tạo cảm hứng cho người khác. Họ thích thể hiện bản thân một cách tự do, không ngại làm nổi bật cá tính và tài năng của mình. Số 3 luôn là tâm điểm của mọi cuộc vui, bởi họ có khả năng truyền tải niềm vui và sự hài hước đến với mọi người xung quanh. Những người này có năng khiếu giao tiếp và khả năng hài hước, giúp họ dễ dàng tạo dựng được tình bạn tốt đẹp và bền vững. Bản tính của họ có một sức hấp dẫn khó cưỡng, không chỉ thu hút bạn bè mà còn cả gia đình và đồng nghiệp.\n' +
        'Số thái độ 3 thường được đánh giá cao về lòng tự trọng và ý thức tự lập. Họ sống với phong cách tự do, không thích bị kiểm soát và rất khó để ai có thể ép buộc họ làm điều mà họ không thích. Tuy nhiên, cũng chính vì tính cách này mà số 3 có thể gặp khó khăn trong việc duy trì kỷ luật và tập trung vào các mục tiêu dài hạn. Để phát huy hết tiềm năng của mình, họ cần học cách kiểm soát năng lượng sáng tạo và xây dựng cho bản thân một kỷ luật vững vàng để thực hiện những hoài bão lớn lao.\n',
    4: 'Chỉ số thái độ của bạn là: 4\n' +
        'Những người có chỉ số thái độ 4 luôn nổi bật bởi tính cách trung thành, đáng tin cậy và tinh thần trách nhiệm cao. Họ là những người đáng để người khác dựa dẫm và tin tưởng, bởi họ luôn giữ vững lập trường và không dễ dàng dao động trước áp lực. Trong công việc, số thái độ 4 có khả năng quản lý và tổ chức rất tốt, luôn đảm bảo mọi thứ được sắp xếp ngăn nắp, gọn gàng. Bản tính cẩn thận và chỉn chu giúp họ có được sự tín nhiệm từ cấp trên và đồng nghiệp.\n' +
        'Bên cạnh đó, số 4 còn được biết đến với tinh thần trách nhiệm cao và khả năng làm việc chăm chỉ. Họ thường là những người không ngại khó khăn, sẵn sàng đảm đương những nhiệm vụ lớn và chịu trách nhiệm cho những gì mình đã làm. Chính tính cách này giúp họ xây dựng được những mối quan hệ bền chặt và lâu dài. Tuy nhiên, số 4 cũng có khuynh hướng tránh xa những rủi ro, không thích mạo hiểm và thích sự an toàn hơn là thử nghiệm những điều mới mẻ. Điều này có thể khiến họ bỏ lỡ một số cơ hội, do đó, lời khuyên cho số 4 là hãy mở lòng đón nhận sự thay đổi để có thể khai phá những tiềm năng tiềm ẩn.\n',
    5: 'Chỉ số thái độ của bạn là: 5\n' +
        'Chỉ số thái độ 5 là biểu tượng của sự tự do, sáng tạo và niềm khao khát khám phá. Những người này không ngại thử thách và luôn sẵn sàng đón nhận những điều mới mẻ. Đối với họ, cuộc sống là một hành trình thú vị, và mỗi trải nghiệm là một cơ hội để trưởng thành. Chính vì vậy, số 5 thường thích du lịch, khám phá và tìm kiếm những cơ hội để trải nghiệm cuộc sống một cách trọn vẹn nhất.\n' +
        'Họ có một tinh thần lạc quan và thái độ tích cực, không dễ gì bị gục ngã trước khó khăn. Điều này khiến họ trở nên sôi động và thu hút, luôn là tâm điểm của sự chú ý trong bất kỳ môi trường nào. Sự linh hoạt, khả năng giao tiếp tuyệt vời và tinh thần phiêu lưu giúp số 5 dễ dàng kết nối với người khác và xây dựng những mối quan hệ xã hội phong phú. Tuy nhiên, chính tính cách phóng khoáng này đôi khi có thể khiến họ trở nên không ổn định và khó kiên định với các mục tiêu dài hạn.\n',
    6: 'Chỉ số thái độ của bạn là: 6\n' +
        'Người có chỉ số thái độ 6 thường sở hữu một trái tim ấm áp, yêu thương và luôn sẵn lòng chăm sóc người khác. Họ là biểu tượng của sự hòa thuận, sự hy sinh và luôn mong muốn giữ cho mọi người xung quanh mình được an toàn và hạnh phúc. Với tính cách đầy bao dung và vị tha, số thái độ 6 rất giỏi trong việc lắng nghe, thấu hiểu và giải quyết những mâu thuẫn trong các mối quan hệ. Họ không chỉ giỏi chăm sóc người khác mà còn biết cách tạo ra một bầu không khí thân thiện, gần gũi, làm cho mọi người cảm thấy được yêu thương và chấp nhận.\n' +
        'Bên cạnh đó, số 6 thường có một tư duy nghệ thuật, yêu thích cái đẹp và có gu thẩm mỹ cao. Họ có thể dễ dàng trở thành những người sáng tạo, nghệ sĩ hoặc những người có đóng góp lớn trong lĩnh vực nghệ thuật và cộng đồng. Tuy nhiên, vì có khuynh hướng ưu tiên lợi ích của người khác, đôi khi số 6 có thể quên mất nhu cầu cá nhân của mình. Lời khuyên cho họ là hãy chú ý đến bản thân hơn, không để bản thân kiệt sức khi liên tục đáp ứng nhu cầu của người khác. Điều này sẽ giúp họ duy trì được sự cân bằng trong cuộc sống và bảo vệ sức khỏe tinh thần của mình.\n',
    7: 'Chỉ số thái độ của bạn là: 7\n' +
        'Số thái độ 7 đại diện cho những người sâu sắc, tư duy phản biện và rất hay tìm tòi về ý nghĩa của cuộc sống. Họ thường có một thế giới nội tâm phong phú, luôn đặt câu hỏi và tìm kiếm câu trả lời cho những điều bí ẩn. Số 7 có xu hướng sống nội tâm và thích suy ngẫm, do đó họ có khả năng nghiên cứu, phân tích và nhìn nhận sự việc ở nhiều góc độ khác nhau. Tính cách tỉ mỉ, chi tiết giúp họ trở thành những người rất giỏi trong lĩnh vực nghiên cứu, học thuật hoặc những công việc đòi hỏi tính phân tích cao.\n' +
        'Tuy nhiên, số 7 cũng có thể trở nên xa cách và khó gần với người khác vì xu hướng sống khép kín của mình. Họ thường dành thời gian để suy nghĩ và phân tích hơn là chia sẻ cảm xúc. Lời khuyên cho số 7 là nên mở lòng và chia sẻ với người khác nhiều hơn, điều này sẽ giúp họ xây dựng được các mối quan hệ tốt đẹp và cũng giúp họ nhìn nhận cuộc sống từ nhiều góc độ hơn. Khi số 7 biết kết nối và chia sẻ, họ sẽ khám phá được nhiều khía cạnh khác của cuộc sống, giúp họ phát triển toàn diện hơn.\n',
    8: 'Chỉ số thái độ của bạn là: 8\n' +
        'Số thái độ 8 tượng trưng cho sự mạnh mẽ, quyết đoán và luôn hướng đến mục tiêu lớn. Những người mang chỉ số này thường có tham vọng lớn, luôn khao khát đạt được thành công và quyền lực. Họ có tư duy tổ chức và khả năng quản lý vượt trội, dễ dàng trở thành người lãnh đạo hoặc giữ những vị trí quan trọng trong công việc. Số 8 không ngại đối diện với khó khăn, thử thách và sẵn sàng làm mọi thứ để đạt được mục tiêu của mình.\n' +
        'Với tính cách quyết đoán và khả năng tổ chức tốt, số 8 thường thu hút được sự tôn trọng từ người khác. Tuy nhiên, đôi khi họ có thể trở nên cứng nhắc hoặc tỏ ra quá thực dụng, chỉ quan tâm đến lợi ích mà quên đi các yếu tố tình cảm. Để cân bằng, số 8 cần học cách lắng nghe và thể hiện sự quan tâm đến cảm xúc của những người xung quanh. Điều này không chỉ giúp họ xây dựng được các mối quan hệ bền chặt mà còn giúp họ trở thành những nhà lãnh đạo được yêu mến và tin tưởng.\n',
    9: 'Chỉ số thái độ của bạn là: 9\n' +
        'Chỉ số thái độ 9 tượng trưng cho lòng nhân ái, sự bao dung và lý tưởng sống cao cả. Những người này có lòng vị tha và luôn hướng đến việc làm tốt cho cộng đồng. Họ thường có cái nhìn rộng lớn, không chỉ quan tâm đến bản thân mà còn đến sự phát triển và hạnh phúc của những người khác. Số 9 có tư duy sâu sắc và thường suy nghĩ đến những giá trị cao đẹp, điều này khiến họ có xu hướng chọn những con đường gắn liền với việc giúp đỡ hoặc đóng góp cho cộng đồng.\n' +
        'Với trái tim đầy nhân ái, số 9 thường được mọi người yêu mến và kính trọng. Tuy nhiên, đôi khi họ có thể quên đi nhu cầu cá nhân vì quá tập trung vào việc giúp đỡ người khác. Lời khuyên cho họ là nên giữ sự cân bằng giữa trách nhiệm với cộng đồng và bản thân, đảm bảo rằng họ không đánh mất đi niềm vui và sự hài lòng trong cuộc sống.\n',
}

export default ChiSoThaiDo