const ChiSoKhuyetThieu = {
  1: 'Số khuyết 1:\nBài học mà bạn cần trải qua là rèn luyện sự tự chủ, độc lập và ý chí vươn lên. Thiếu số 1 trong biểu đồ ngày sinh có thể khiến bạn gặp khó khăn hơn trong việc đưa ra quyết định, làm giảm khả năng hành động mạnh mẽ, quyết đoán. Bạn có thể sẽ trải qua nhiều thử thách trong công việc và cuộc sống, như những bài học để rèn giũa khả năng lãnh đạo và tự chịu trách nhiệm. Những sự kiện đến với bạn có thể là cơ hội để phát triển lòng tự tin, khẳng định bản thân và dần học cách làm chủ cuộc sống.',
  2: 'Số khuyết 2:\nBài học của bạn là học cách bày tỏ tình cảm, xây dựng kết nối và đặt lợi ích chung lên hàng đầu. Khi thiếu số 2, bạn có thể thấy mình khó hòa đồng, ít đồng cảm, và gặp khó khăn trong việc hiểu được cảm xúc của người khác. Điều này đôi khi tạo ra ấn tượng rằng bạn lạnh lùng, ít quan tâm, hoặc khó hợp tác, dẫn đến việc khó khăn trong xây dựng các mối quan hệ lâu dài. Những sự kiện liên quan đến mâu thuẫn, rạn nứt mối quan hệ có thể xuất hiện như là những bài học giúp bạn trở nên nhạy cảm và dễ chia sẻ hơn với mọi người xung quanh.',
  3: 'Số khuyết 3:\nBài học của bạn là nuôi dưỡng sự lạc quan, vui vẻ, sáng tạo và khả năng giao tiếp. Khi thiếu số 3, bạn có thể cảm thấy mình khó bày tỏ cảm xúc, dễ căng thẳng và không linh hoạt. Việc mở rộng các mối quan hệ xã hội, khơi dậy sự sáng tạo và học cách giao tiếp cởi mở sẽ giúp bạn phát triển toàn diện hơn. Những sự kiện trong cuộc sống có thể tạo ra thử thách trong việc kết nối, đòi hỏi bạn mở lòng hơn, tìm cách truyền đạt cảm xúc, ý tưởng một cách rõ ràng và duy trì sự linh hoạt trong mọi tình huống.',
  4: 'Số khuyết 4:\nBài học của bạn là học cách xây dựng tính chi tiết, tổ chức và lập kế hoạch. Khi thiếu số 4, bạn có thể cảm thấy thiếu ổn định và dễ bị lúng túng trong công việc do thiếu kế hoạch rõ ràng. Những lúc gặp khó khăn, bạn có thể nhận ra tầm quan trọng của sự tỉ mỉ, kiên trì và tổ chức để đạt được kết quả mong muốn. Cuộc sống sẽ thử thách bạn bằng những tình huống đòi hỏi phải lên kế hoạch chặt chẽ, để bạn dần phát triển và củng cố kỹ năng quản lý công việc và sắp xếp cuộc sống một cách có hệ thống.',
  5: 'Số khuyết 5:\nBài học của bạn là khám phá sự tự do, dấn thân và tìm kiếm trải nghiệm mới. Thiếu số 5 sẽ làm cuộc sống của bạn đôi khi trở nên nhàm chán, đơn điệu và thiếu màu sắc. Bạn có thể thấy hài lòng với cuộc sống an toàn, ổn định, nhưng nếu mở lòng, bạn sẽ nhận ra những trải nghiệm tuyệt vời mà thế giới có thể mang lại. Hãy thử dấn thân, khám phá điều mới lạ, bạn sẽ thấy cuộc sống phong phú hơn nhiều. Việc vượt qua những ranh giới an toàn sẽ giúp bạn mở rộng tư duy và trưởng thành hơn.',
  6: 'Số khuyết 6:\nBài học của bạn là thể hiện sự quan tâm, chăm sóc, sự tinh tế và thẩm mỹ. Thiếu số 6, bạn có thể gặp khó khăn trong việc thể hiện cảm xúc và sự đồng cảm. Điều này đôi khi khiến bạn trông khô khan và ít quan tâm, dù thực chất bên trong bạn giàu tình cảm. Việc bày tỏ cảm xúc một cách chân thành sẽ giúp bạn không chỉ kết nối sâu hơn với những người xung quanh mà còn giải tỏa được sự căng thẳng trong lòng. Cuộc sống sẽ cho bạn những cơ hội để học cách quan tâm, tạo dựng các mối quan hệ gần gũi hơn và bày tỏ tình cảm một cách tự nhiên.',
  7: 'Số khuyết 7:\nBài học của bạn là học cách chiêm nghiệm, đúc kết và phát triển nội ngã. Khi thiếu số 7, bạn có thể có xu hướng nhìn cuộc sống một cách thực tiễn quá mức, thiếu sự tìm hiểu sâu xa về tư tưởng và triết lý. Điều này có thể làm giảm khả năng nhìn nhận sâu rộng, ngăn cản bạn tìm thấy ý nghĩa cao hơn trong cuộc sống. Những sự kiện trong đời sẽ giúp bạn học cách lắng đọng, đào sâu suy nghĩ và phát triển tinh thần, giúp bạn trở nên chín chắn, có chiều sâu trong tư duy và có khả năng khám phá ý nghĩa cuộc sống.',
  8: 'Số khuyết 8:\nBài học của bạn là nhận thức rõ về sự thực tiễn, trách nhiệm tài chính và vai trò của vật chất trong cuộc sống. Thiếu số 8 có thể khiến bạn ít chú trọng đến vật chất, dẫn đến khó khăn trong việc quản lý tài chính, và dễ rơi vào tình trạng thiếu thốn. Những thử thách tài chính hoặc trong công việc sẽ giúp bạn hiểu hơn về tầm quan trọng của sự thực tiễn, sự cân đối giữa nhu cầu tinh thần và vật chất, từ đó tạo động lực cho bạn phát triển trong sự nghiệp và tạo nền tảng ổn định cho cuộc sống.',
  9: 'Số khuyết 9:\nBài học của bạn là phát triển lòng bao dung, độ lượng và sự quan tâm đến cộng đồng, người khác. Khi thiếu số 9, bạn có thể trở nên tự chủ và quan tâm nhiều đến bản thân hơn là tập thể. Bạn có thể khó mở lòng để giúp đỡ người khác, hoặc ít muốn dấn thân vào các hoạt động vì cộng đồng. Cuộc sống sẽ mang đến những cơ hội để bạn mở rộng tầm nhìn, học cách chia sẻ, và đem lại lợi ích cho những người xung quanh. Việc bày tỏ lòng nhân ái và đóng góp cho xã hội sẽ giúp bạn tìm thấy ý nghĩa lớn hơn và thêm sự trọn vẹn trong cuộc sống.'
}
export default ChiSoKhuyetThieu
