const ChiSoLinhHon = {
    1: 'Bạn mang chỉ số linh hồn 1: Người mang năng lượng tự tin và kiên cường\n' +
    'Người có Chỉ số Linh hồn 1 là mẫu người có tính cách mạnh mẽ và độc lập. Họ không chỉ mang khát khao sống là chính mình mà còn luôn cố gắng để khẳng định cá tính riêng biệt. Đối với họ, việc thể hiện bản thân một cách tự do, không bị ràng buộc là điều vô cùng quan trọng. Người mang chỉ số này có bản năng cạnh tranh mạnh mẽ, dễ thể hiện rõ trong môi trường tập thể như nơi làm việc, đội nhóm, hoặc các lớp học. Họ không ngừng nỗ lực, cố gắng để đứng vững và luôn tiến lên phía trước, dù gặp phải bao nhiêu thử thách, bởi họ khao khát chiến thắng và muốn được thừa nhận năng lực thật sự của mình.\n' +
    'Những người này còn có một khía cạnh bên trong khá nhạy cảm: từ sâu thẳm, họ luôn mong muốn nhận được sự công nhận từ người khác. Dù bên ngoài thể hiện một vẻ tự tin và kiên cường, nhưng bất cứ khi nào công sức của họ không được coi trọng hay bị phủ nhận, họ dễ rơi vào trạng thái thất vọng. Chính vì vậy, đối với người có Linh hồn số 1, sự khích lệ, động viên đóng vai trò rất quan trọng. Họ sẽ cảm thấy thoải mái và tự tin hơn khi được động viên, thay vì bị chỉ trích hay phê bình.\n' +
    'Người có Linh hồn số 1 thường rất thích cảm giác chiến thắng và chinh phục những thử thách. Họ không ngại đương đầu với khó khăn, vì mỗi lần vượt qua một thử thách cũng là một bước tiến để khẳng định bản thân. Từ khi sinh ra, dòng máu nhiệt huyết và ý chí mạnh mẽ đã chảy trong huyết quản của họ, khiến họ luôn tràn đầy năng lượng và quyết tâm. Họ không thích gò bó, không muốn đi theo con đường mà người khác đã chọn, vì họ cần tự do để sáng tạo và bứt phá. Những người có chỉ số này thích tạo ra lối đi riêng, khác biệt và đầy cá tính. Khi bị ép buộc phải tuân theo một khuôn mẫu nào đó, họ thường cảm thấy bức bối, thậm chí khó chịu.\n' +
    'Với tính cách độc lập và mạnh mẽ như vậy, người mang Linh hồn số 1 luôn đề cao sự tự giác và năng lực của chính mình. Họ sẵn sàng đối mặt với thử thách và không ngừng cố gắng để hoàn thiện bản thân. Tuy nhiên, họ cũng cần một không gian tinh thần thoải mái, nơi mà những nỗ lực của họ được ghi nhận và động viên kịp thời. Những ai làm cha mẹ hoặc người quản lý của người mang Linh hồn số 1 nên biết cách khen ngợi và khích lệ họ thường xuyên. Khi chỉ ra sai sót hoặc lỗi lầm, hãy thể hiện bằng sự mềm mỏng, hòa nhã, để tránh làm họ cảm thấy bị xem nhẹ hay không được coi trọng.\n',
    2: 'Bạn mang chỉ số linh hồn 2: Người khéo léo và yêu hòa bình\n' +
    'Người có Chỉ số Linh hồn 2 là những người khéo léo trong giao tiếp và luôn tìm kiếm sự thoải mái, hòa hợp trong các mối quan hệ. Họ sống vì tình cảm và luôn mong muốn duy trì sự hòa bình và cân bằng xung quanh mình. Vì vậy, người có chỉ số này luôn nỗ lực xây dựng và duy trì những mối quan hệ tích cực và vui vẻ. Khát khao kết nối và chia sẻ với người khác khiến họ trở thành những người bạn, người đồng nghiệp ấm áp, dễ gần.\n' +
    'Người có Linh hồn số 2 còn rất thấu hiểu người khác, luôn cố gắng hạn chế xung đột và thường đảm nhận vai trò hòa giải. Họ luôn mong muốn mọi người xung quanh cảm thấy dễ chịu, thân thiện và hòa bình, điều này làm cho sự xuất hiện của họ trở thành nguồn năng lượng tích cực và ổn định. Khả năng nhìn nhận được cả mặt tích cực và tiêu cực của một vấn đề giúp họ trở nên sáng suốt, lý trí và khách quan.\n' +
    'Không chỉ dừng lại ở khía cạnh tình cảm, người có Linh hồn số 2 còn có khả năng chữa lành và cân bằng trong mọi mối quan hệ. Họ luôn sẵn lòng hỗ trợ người khác vượt qua khó khăn, là điểm tựa tinh thần cho những người thân yêu. Tình cảm chân thành và lòng yêu thương của họ lan tỏa đến mọi người xung quanh, giúp mang lại sự bình yên và dễ chịu trong những thời điểm thử thách.\n',
    3: 'Bạn mang chỉ số linh hồn 3: Người mang năng lượng tươi mới và sáng tạo\n' +
    'Người có Chỉ số Linh hồn 3 là những người luôn tràn đầy sức sống và năng lượng tích cực. Họ khao khát được sống và làm việc trong môi trường vui vẻ, sáng tạo và tự do thể hiện cá tính của mình. Với tinh thần vui tươi và trẻ trung, họ thường mang đến cho mọi người xung quanh cảm giác thoải mái và sự hài hước. Sự cổ vũ và khuyến khích là điều mà người mang chỉ số này rất yêu thích, vì nó giúp họ phát huy tối đa tiềm năng của bản thân.\n' +
    'Người mang Linh hồn số 3 cũng rất sáng tạo và không ngại thử nghiệm những điều mới mẻ. Họ thích phá vỡ giới hạn, đi theo cách riêng của mình và tạo ra những dấu ấn độc đáo. Chính vì điều này mà họ luôn tỏa sáng với nguồn năng lượng nhiệt huyết và năng động. Sự yêu thích sáng tạo và khả năng truyền cảm hứng giúp họ trở thành những người bạn, đồng nghiệp lý tưởng.\n' +
    'Không chỉ có niềm đam mê sáng tạo, người có Linh hồn số 3 còn rất yêu thích việc giúp đỡ người khác. Họ luôn sẵn lòng hỗ trợ và giúp đỡ khi ai đó cần. Cảm giác được cho đi và nhận lại những điều tốt đẹp mang lại cho họ niềm vui và sự hạnh phúc. Sự lương thiện trong con người của họ giống như ánh mặt trời ấm áp, lan tỏa niềm vui và sự lạc quan đến mọi người xung quanh.\n',
    4: 'Bạn mang chỉ số linh hồn 4: Người cẩn trọng và cầu toàn\n' +
    'Người có Chỉ số Linh hồn 4 là những người chu toàn và cẩn thận trong mọi việc. Họ luôn hướng tới sự hoàn hảo, chú ý từng chi tiết và không ngừng học hỏi để nâng cao bản thân. Người mang chỉ số này luôn trau dồi kiến thức, tích lũy kinh nghiệm và am hiểu rộng về nhiều lĩnh vực, điều này giúp họ trở thành người có kiến thức sâu rộng và dễ gần. Trong giao tiếp, họ thường là người đóng góp nhiều thông tin bổ ích và thích hợp cho các cuộc trò chuyện.\n' +
    'Người có Linh hồn số 4 cũng rất yêu thương gia đình, coi trọng tình thân và luôn tìm kiếm sự an toàn, ổn định. Đối với họ, gia đình là nền tảng, là nơi họ tìm thấy sự bình yên. Nếu sinh ra trong một môi trường gia đình ấm áp, họ sẽ dễ dàng trở nên thoải mái, dịu dàng và yêu thương hơn.\n' +
    'Với bản chất chăm chỉ và chu đáo, người mang Linh hồn số 4 là những nhân viên, nhà quản lý tận tụy, luôn cống hiến hết mình trong công việc. Họ luôn tự giác và có trách nhiệm, từ đó tạo nên sự ổn định, tổ chức tại nơi làm việc, gia đình hay thậm chí là cộng đồng.\n',
    5: 'Bạn mang chỉ số linh hồn 5: Người yêu tự do và thích khám phá\n' +
    'Người có Chỉ số Linh hồn 5 mang trong mình bản tính thích tự do và luôn khao khát khám phá những điều mới mẻ. Họ không thích bị ràng buộc vào bất kỳ khuôn khổ nào, luôn tìm kiếm sự đổi mới và đa dạng trong cuộc sống. Với năng lượng của người phiêu lưu, họ thích được trải nghiệm và tìm hiểu những điều khác biệt, đặc biệt là ở những lĩnh vực chưa được khám phá hoặc những nơi ít người biết đến. Sự tò mò là động lực thúc đẩy họ mở rộng tầm nhìn và hiểu biết, điều này giúp họ trở thành những người có tư duy cởi mở và luôn tràn đầy năng lượng.\n'+
    'Người có Linh hồn số 5 còn rất hòa đồng, vui vẻ và linh hoạt trong giao tiếp. Họ dễ dàng thích nghi với các môi trường và tình huống mới, biết cách ứng phó và xử lý linh hoạt trước mọi thử thách. Chính sự cởi mở và hòa nhã này giúp họ tạo dựng được nhiều mối quan hệ tốt đẹp và luôn có nhiều bạn bè bên cạnh.\n'+
    'Tuy nhiên, người có Linh hồn số 5 cũng có thể gặp khó khăn trong việc duy trì sự ổn định. Sự đam mê tìm kiếm sự tự do và trải nghiệm mới khiến họ khó kiên nhẫn khi phải gắn bó với một điều gì đó quá lâu. Do đó, để giữ cân bằng trong cuộc sống, họ cần học cách tạo ra một số nguyên tắc cho bản thân, dù là đơn giản nhưng sẽ giúp họ tập trung vào mục tiêu dài hạn hơn.\n',
    6:'Bạn mang chỉ số linh hồn 6: Người yêu gia đình và tận tâm\n' +
    'Người có Chỉ số Linh hồn 6 là những người yêu thương, chu đáo và rất coi trọng gia đình. Họ luôn mong muốn đem lại sự ấm áp, an lành cho những người xung quanh, đặc biệt là những người thân yêu. Với tính cách giàu lòng trắc ẩn, họ sẵn sàng giúp đỡ người khác, không ngại khó khăn để làm cho mọi người xung quanh cảm thấy hạnh phúc và yên bình. Sự tận tâm này không chỉ dừng lại ở gia đình mà còn lan tỏa đến bạn bè, đồng nghiệp và cả cộng đồng.\n' +
    'Với tính cách cẩn thận và tinh thần trách nhiệm cao, người có Linh hồn số 6 thường là người chăm lo cho gia đình, là người bạn đáng tin cậy, luôn có mặt khi ai đó cần. Họ dễ dàng nhận biết được nhu cầu và mong muốn của người khác, sẵn lòng lắng nghe và chia sẻ những vấn đề khó khăn mà người xung quanh đang gặp phải.\n' +
    'Tuy nhiên, người có Linh hồn số 6 đôi khi dễ cảm thấy áp lực khi phải đối mặt với những trách nhiệm lớn, đặc biệt là khi phải chăm lo cho mọi người xung quanh mà không dành thời gian cho bản thân. Điều này có thể khiến họ trở nên mệt mỏi hoặc căng thẳng. Do đó, họ cần học cách cân bằng giữa việc chăm sóc người khác và yêu thương chính mình để duy trì được năng lượng tích cực lâu dài.\n',
    7:'Bạn mang chỉ số linh hồn 7: Người sâu sắc và tâm linh\n' +
    'Người mang Chỉ số Linh hồn 7 thường có thiên hướng suy ngẫm, sâu sắc và tâm linh. Họ không ngừng đặt câu hỏi về cuộc sống, ý nghĩa của sự tồn tại và tìm kiếm tri thức ở những tầng sâu của thế giới. Với bản tính thích học hỏi và tìm tòi, họ thường dành thời gian để nghiên cứu, phân tích và khám phá những kiến thức mới, đặc biệt là những kiến thức về tâm linh, triết học, hay những lĩnh vực đòi hỏi sự tư duy cao.\n' +
    'Họ là những người thích sự yên tĩnh, có đời sống nội tâm phong phú và đôi khi thích cô độc để tập trung vào những suy ngẫm của mình. Người có Linh hồn số 7 thường có khả năng thấu hiểu sâu sắc, có khả năng đọc vị tâm hồn người khác và dễ dàng đồng cảm với những ai có hoàn cảnh khó khăn.\n' +
    'Với tính cách sâu sắc và yêu thích sự trầm lắng, họ có thể dễ cảm thấy lạc lõng nếu xung quanh là những người không cùng tần số với mình. Vì vậy, để cân bằng cuộc sống, họ nên tìm kiếm những người có cùng sở thích, cùng quan điểm để có thể chia sẻ và đồng hành.\n',
    8:'Bạn mang chỉ số linh hồn 8: Người mạnh mẽ và tham vọng\n'+
    'Người có Chỉ số Linh hồn 8 là những người có tham vọng lớn, khát khao đạt được thành công và quyền lực. Họ luôn muốn vươn tới đỉnh cao và không ngừng cố gắng để xây dựng một sự nghiệp vững chắc, khẳng định bản thân trong xã hội. Sự kiên trì và tinh thần chiến đấu là hai yếu tố chủ đạo giúp họ đạt được nhiều thành công và xây dựng vị thế của mình.\n'+
    'Với tính cách quyết đoán và mạnh mẽ, người có Linh hồn số 8 thường là người lãnh đạo giỏi, có khả năng đưa ra những quyết định đúng đắn và nhanh chóng trong công việc. Họ luôn đặt mục tiêu cao và không ngần ngại đối mặt với những thử thách để đạt được mục tiêu đó. Tuy nhiên, chính vì quá tập trung vào công việc và thành công, đôi khi họ dễ rơi vào trạng thái căng thẳng hoặc bỏ quên nhu cầu cá nhân và gia đình.\n'+
    'Người có Linh hồn số 8 cần học cách cân bằng giữa công việc và cuộc sống cá nhân, tìm hiểu thêm về giá trị của tình cảm và các mối quan hệ để không chỉ đạt được thành công vật chất mà còn có được hạnh phúc tinh thần.\n',
    9:'Bạn mang chỉ số linh hồn 9: Người giàu lòng nhân ái và lý tưởng cao đẹp\n'+
    'Người mang Chỉ số Linh hồn 9 thường là những người sống với lý tưởng cao đẹp, luôn mong muốn đóng góp cho xã hội và mang lại những điều tốt đẹp cho cộng đồng. Họ là những người giàu lòng nhân ái, luôn sẵn lòng giúp đỡ người khác mà không toan tính lợi ích cá nhân. Đối với họ, giá trị tinh thần, tình thương và lòng trắc ẩn luôn là điều quan trọng nhất.\n'+
    'Người có Linh hồn số 9 thường rất cảm thông với nỗi đau của người khác, sẵn lòng hy sinh vì lợi ích chung và không ngừng cố gắng để làm cho thế giới trở nên tốt đẹp hơn. Chính lòng nhân ái và ý thức trách nhiệm với cộng đồng đã biến họ trở thành những nhà từ thiện, những người truyền cảm hứng lớn trong xã hội.\n'+
    'Tuy nhiên, vì luôn đặt lợi ích của người khác lên trên hết, họ có thể dễ bị tổn thương hoặc kiệt sức nếu không biết giữ gìn sức khỏe tinh thần. Họ cần học cách dành thời gian cho bản thân, chăm sóc cho cả nhu cầu cá nhân để có thể tiếp tục lan tỏa tình thương đến mọi người một cách bền vững.\n',
}

export default ChiSoLinhHon