const ChiSoTinhCach = {
    1:'Bạn mang số nhân cách 1: Người Tiên Phong Độc Lập và Năng Động\n' +
    'Người mang Số Nhân cách 1 thường sở hữu năng lượng mạnh mẽ và đầy nhiệt huyết của một người tiên phong thực thụ. Đây là người luôn khao khát dẫn đầu, không ngừng nghỉ trong việc khẳng định bản thân và chinh phục những đỉnh cao mới. Họ không chỉ tự tin vào năng lực mà còn luôn tin rằng mình có khả năng vượt trội hơn người khác. Chính lòng tự tin và quyết tâm này giúp họ trở thành những nhà lãnh đạo tự nhiên, biết cách đưa ra những quyết định táo bạo và kiên định.\n' +
    'Người có Số Nhân cách 1 thường không thích bị kiểm soát hay điều khiển, vì họ tin rằng chỉ khi mình làm chủ cuộc sống thì mới có thể phát huy hết tiềm năng. Với họ, thử thách và rủi ro không phải là điều đáng sợ, mà là cơ hội để phát triển và bứt phá. Điều này giúp họ trở thành người dẫn dắt các dự án, hoạt động với tư duy sáng tạo và luôn tìm cách hoàn thành công việc một cách hiệu quả nhất.\n' +
    'Tuy nhiên, tính cách độc lập và cái tôi mạnh mẽ đôi khi có thể khiến người có Số Nhân cách 1 gặp khó khăn trong việc hợp tác với người khác. Họ cần học cách cởi mở, lắng nghe và chấp nhận ý kiến đóng góp từ mọi người để không chỉ phát triển bản thân mà còn tạo ra môi trường làm việc hòa hợp hơn.\n',
    2:'Bạn mang số nhân cách 2: Sứ Giả Hòa Bình\n'+
    'Số Nhân cách 2 đại diện cho sự hòa nhã và tinh thần hòa bình. Đây là người biết lắng nghe, nhạy cảm và luôn cố gắng duy trì sự hòa hợp trong mọi mối quan hệ. Họ được mệnh danh là “người kiến tạo hòa bình” bởi sự hiện diện của họ thường mang đến cảm giác yên bình và thân thiện. Với bản tính tinh tế, người có Số Nhân cách 2 luôn chú trọng đến cảm xúc của người khác, coi trọng mối quan hệ cá nhân và dễ dàng đồng cảm với những ai đang gặp khó khăn.\n'+
    'Người mang Số Nhân cách 2 rất tôn trọng tình bạn và tình yêu, luôn sẵn lòng hy sinh để giữ vững các mối quan hệ quý giá. Tuy nhiên, chính sự nhạy cảm và lòng tốt này đôi khi có thể khiến họ dễ bị tổn thương. Vì sẵn lòng giúp đỡ người khác, đôi khi họ dễ bị lợi dụng hoặc lấn át. Để cân bằng, họ cần học cách thiết lập ranh giới rõ ràng và bảo vệ bản thân khỏi những tổn thương không đáng có.\n'+
    'Khi gặp phải xung đột hoặc bất hòa, người có Số Nhân cách 2 thường trở thành người đứng ra hòa giải, giúp các bên đối thoại và tìm ra giải pháp chung. Họ sở hữu khả năng giao tiếp khéo léo và biết cách xây dựng cầu nối giữa những mối quan hệ tưởng chừng như khó dung hòa.\n',
    3:'Bạn mang số nhân cách 3: Hài Hước và Lôi Cuốn\n'+
    'Người mang Số Nhân cách 3 luôn toát lên vẻ hài hước, thân thiện và cởi mở. Họ có khả năng giao tiếp xuất sắc, dễ dàng chiếm được cảm tình của mọi người xung quanh nhờ khả năng diễn đạt linh hoạt và phong cách cuốn hút. Người có Số Nhân cách 3 thường được ví như “người nghệ sĩ” bởi họ không chỉ giỏi giao tiếp mà còn có óc sáng tạo phong phú, biết cách truyền cảm hứng và tạo niềm vui cho người khác.\n'+
    'Người mang Số Nhân cách 3 rất quan tâm đến ngoại hình, phong cách và lời nói. Với họ, mỗi cuộc trò chuyện đều là cơ hội để thể hiện bản thân một cách thú vị và hài hước. Bản chất năng động và tích cực giúp họ nhanh chóng thu hút sự chú ý và tạo dựng nhiều mối quan hệ tốt đẹp. Tuy nhiên, họ cũng dễ bị phụ thuộc vào sự công nhận và khen ngợi từ người khác để duy trì tinh thần lạc quan.\n'+
    'Với sự yêu thích sáng tạo, người có Số Nhân cách 3 thường phù hợp với các công việc đòi hỏi sự linh hoạt và không ngừng đổi mới. Họ cần môi trường đầy cảm hứng để phát huy hết tiềm năng, và những thử thách mới luôn là nguồn động lực để họ tiến về phía trước.\n',
    4:'Bạn mang số nhân cách 4:  Nghiêm Túc và Trí Tuệ\n' +
    'Người có Số Nhân cách 4 là người thực tế, nghiêm túc và có kỷ luật. Đây là những người đặt nặng giá trị của sự kiên trì, tính kỷ luật và luôn chú trọng đến chi tiết. Họ là mẫu người chăm chỉ, không ngại khó khăn và sẵn sàng làm việc đến nơi đến chốn để đạt được mục tiêu. Người có Số Nhân cách 4 thường rất tin cậy và là người mà bạn bè, đồng nghiệp có thể nhờ cậy trong những lúc khó khăn.\n'+
    'Với tư duy logic và kỹ năng phân tích sắc bén, người có Số Nhân cách 4 thường có khả năng học hỏi nhanh và nắm bắt thông tin chính xác. Họ tự hào về khả năng của mình, và thường không dễ dàng thay đổi quan điểm trừ khi nhận được một lập luận thật sự thuyết phục. Sự kiên định trong lập trường và cái nhìn rõ ràng về mọi vấn đề giúp họ đạt được nhiều thành công trong công việc và các mối quan hệ.\n' +
    'Tuy nhiên, sự cứng nhắc và bám chặt vào nguyên tắc có thể khiến người có Số Nhân cách 4 trở nên bảo thủ. Để phát triển toàn diện hơn, họ cần học cách linh hoạt và chấp nhận những quan điểm mới mẻ, để bản thân không bị đóng khung trong tư duy hạn chế.\n',
    5:'Bạn mang số nhân cách 5:  Đam Mê và Khát Vọng\n' +
    'Số Nhân cách 5 biểu trưng cho sự tự do, năng lượng và tinh thần khám phá. Người có Số Nhân cách 5 là những cá nhân đam mê cuộc sống, thích phiêu lưu và luôn tràn đầy nhiệt huyết. Họ không thích bị bó buộc trong một môi trường gò bó, mà luôn tìm kiếm sự đổi mới, kích thích để phát triển bản thân. Sự năng động và sôi nổi giúp họ trở thành trung tâm của mọi cuộc vui, là người truyền cảm hứng cho những người xung quanh.\n'+
    'Người có Số Nhân cách 5 không ngừng sáng tạo và luôn tìm cách đưa ra những ý tưởng độc đáo. Họ có khả năng thích nghi với nhiều môi trường khác nhau, từ đó dễ dàng phát triển sự nghiệp trong các lĩnh vực đa dạng. Tuy nhiên, vì thích khám phá và theo đuổi những trải nghiệm mới, họ có thể dễ dàng bỏ lỡ những cơ hội quý báu khi không tập trung vào một con đường cụ thể.\n' +
    'Để đạt được sự thành công bền vững, người có Số Nhân cách 5 cần học cách kiên trì, giữ vững định hướng và không để bản thân bị phân tâm bởi quá nhiều lựa chọn hấp dẫn.\n',
    6:'Bạn mang số nhân cách 6:  Nhân Ái và Uy Tín\n' +
    'Người có Số Nhân cách 6 là biểu tượng của tình yêu thương, lòng nhân ái và trách nhiệm cao cả. Họ là những người luôn mong muốn đem lại hạnh phúc, sự an lành cho gia đình và những người xung quanh. Với trái tim nhân hậu, họ sẵn sàng hy sinh vì lợi ích của người khác, luôn chăm sóc, bảo vệ và mang lại cảm giác an toàn cho mọi người.\n'+
    'Người mang Số Nhân cách 6 rất giỏi trong việc quản lý, hỗ trợ và xây dựng một tổ chức hoặc gia đình vững mạnh. Họ là mẫu người của gia đình, luôn biết cách chăm lo và nuôi dưỡng mọi thành viên. Tuy nhiên, vì quá quan tâm đến người khác, họ đôi khi quên mất việc chăm sóc bản thân, dễ bị mệt mỏi hoặc kiệt sức.\n' +
    'Người có Số Nhân cách 6 cần học cách tạo ranh giới lành mạnh, không nên làm mọi thứ chỉ để làm hài lòng người khác. Việc giữ vững lập trường, luôn coi trọng bản thân sẽ giúp họ cân bằng được cảm xúc và duy trì năng lượng lâu dài.\n',
    7:'Bạn mang số nhân cách 7:  Huyền Bí và Sâu Sắc\n' +
    'Số Nhân cách 7 là những cá nhân sâu sắc, uyên bác và rất tập trung. Họ có xu hướng hướng nội, thích tìm hiểu các khía cạnh sâu xa của cuộc sống và thường dành thời gian cho những suy ngẫm triết lý. Người mang Số Nhân cách 7 thường có trực giác tốt, là người thông thái và biết lắng nghe.\n'+
    'Mặc dù ít nói, họ lại có khả năng quan sát nhạy bén và nắm bắt thông tin nhanh chóng. Người có Số Nhân cách 7 thích sự yên tĩnh, thích không gian riêng tư và thường không thích sự ồn ào. Khi cần, họ vẫn là người có khả năng lãnh đạo và dẫn dắt, nhờ khả năng kiến thức và sự chuyên nghiệp, tập trung của họ trong quá trình làm việc của họ. Bên cạnh đó, họ cũng là người có trực giác vô cùng nhạy bén, có sự sâu sắc trong tính cách của bản thân.\n',
    8:'Bạn mang số nhân cách 8:  Kỷ Luật và Sáng Suốt\n' +
    'Người có Số Nhân cách 8 thường được biết đến với tính cách mạnh mẽ, kỷ luật và khát khao thành công. Họ là những cá nhân kiên định, luôn hướng đến mục tiêu cao cả và không ngừng phấn đấu để đạt được thịnh vượng, quyền lực và sự công nhận. Người mang Số Nhân cách 8 có sự tự tin và ý chí mạnh mẽ, sẵn sàng đối mặt với mọi thử thách để khẳng định bản thân và vượt qua những giới hạn cá nhân.\n'+
    'Khả năng nhìn nhận vấn đề một cách sáng suốt, không bị cảm xúc chi phối, giúp họ đưa ra những quyết định chính xác và hiệu quả trong công việc. Họ cũng là người nguyên tắc, coi trọng đạo đức nghề nghiệp và thường yêu cầu cao ở bản thân cũng như ở những người xung quanh. Điều này khiến họ trở thành những nhà lãnh đạo lý tưởng và người cố vấn đáng tin cậy.\n' +
    'Tuy nhiên, đôi khi sự quyết đoán và cứng rắn có thể khiến người có Số Nhân cách 8 trở nên hơi cứng nhắc và khó tiếp nhận ý kiến của người khác. Để thành công bền vững, họ cần học cách lắng nghe và cởi mở hơn, xây dựng mối quan hệ hòa hợp và hợp tác hiệu quả. Bằng cách duy trì sự cân bằng giữa kỷ luật và linh hoạt, người mang Số Nhân cách 8 sẽ đạt được sự thành công toàn diện và xây dựng uy tín lâu dài.\n',
    9:'Bạn mang số nhân cách 9:  Tình Cảm và Nhân Hậu\n' +
    'Người sở hữu Số Nhân cách 9 là hiện thân của sự nhân ái, độ lượng và lý tưởng cao cả. Họ có trực giác nhạy bén, trí tuệ sâu sắc và trái tim luôn hướng đến cộng đồng. Người mang Số Nhân cách 9 thường rất nhạy cảm, dễ đồng cảm với những hoàn cảnh khó khăn và sẵn sàng giúp đỡ người khác mà không đòi hỏi sự đáp trả. Đây là người luôn đặt lợi ích chung lên trên hết, coi trọng các giá trị tinh thần và cống hiến hết mình vì những lý tưởng lớn lao.\n'+
    'Với khả năng lãnh đạo tự nhiên, người có Số Nhân cách 9 thường được mọi người tin tưởng và kỳ vọng. Họ là những người hướng dẫn đáng tin cậy, biết cách động viên và truyền cảm hứng cho những người xung quanh. Những tình huống khó khăn không làm họ chùn bước mà ngược lại, chỉ làm tăng thêm sức mạnh nội tại và sự quyết tâm của họ. Sự kiên định và lý tưởng mạnh mẽ giúp họ trở thành những người dẫn đầu đáng kính trọng trong các cộng đồng.\n' +
    'Dẫu vậy, do quá nhạy cảm và tận tâm với người khác, đôi khi người có Số Nhân cách 9 dễ bị tổn thương khi không được người khác hiểu rõ hoặc khi lý tưởng không được đáp ứng. Để duy trì sự cân bằng, họ cần học cách bảo vệ cảm xúc của mình, tập trung vào những điều tích cực và tránh để bản thân bị cuốn vào những chuyện không đáng. Khi có thể duy trì lòng kiên nhẫn và lòng bao dung, người mang Số Nhân cách 9 sẽ không chỉ đạt được thành công mà còn trở thành biểu tượng của tình yêu thương và lòng nhân ái trong cộng đồng.\n',
}

export default ChiSoTinhCach