const ChiSoSuMenh =
  {
      1:'Chỉ số sứ mệnh của bạn là: 1\n' +
      'Những người sở hữu chỉ số sứ mệnh số 1 trong thần số học là những cá nhân với cá tính mạnh mẽ, luôn muốn dẫn dắt và làm chủ cuộc sống của mình. Họ được biết đến với tinh thần độc lập, yêu thích tự do, không ngại thử thách và thường có cách làm việc riêng biệt, không thích bị người khác áp đặt hay gò bó. Trong mọi tình huống, người mang chỉ số này luôn có khát khao nổi bật và khẳng định vị trí của mình trong xã hội. Chính sự đam mê với thành công đã tạo động lực mạnh mẽ để họ cố gắng hết mình, không ngừng khám phá giới hạn bản thân và luôn tiến bước về phía trước.\n' +
      'Với bản chất độc lập và ý chí mãnh liệt, những người mang chỉ số sứ mệnh 1 thường thích nghi nhanh chóng với những vị trí đòi hỏi tính trách nhiệm cao. Khi đối mặt với thách thức, họ không dễ dàng bị khuất phục; ngược lại, họ xem đó như cơ hội để vượt qua và phát triển thêm. Sự kiên cường và quyết đoán giúp họ dễ dàng đạt được thành công, vượt trội trong nhiều lĩnh vực. Họ không ngại khó khăn, sẵn sàng dấn thân và luôn biết cách tận dụng các nguồn lực để đạt được kết quả mong muốn.\n'+
      'Hơn nữa, chỉ số sứ mệnh 1 còn đại diện cho khả năng sáng tạo tuyệt vời và phong cách làm việc linh hoạt. Họ không chỉ có khả năng tạo ra những ý tưởng mới lạ mà còn biết cách biến chúng thành hiện thực với tốc độ đáng kinh ngạc. Nhờ vào năng lượng dồi dào và tinh thần làm việc nhiệt huyết, những người này có thể truyền cảm hứng cho những người xung quanh, khiến mọi người luôn cảm nhận được sự sôi nổi và tích cực trong con người họ. Khả năng thu hút sự chú ý và sự chủ động khiến họ trở thành tâm điểm trong các hoạt động, dễ dàng tạo dựng uy tín và ảnh hưởng trong môi trường công việc.\n'+
      'Không những vậy, người mang chỉ số sứ mệnh 1 còn có tài năng lãnh đạo thiên bẩm. Họ có tầm nhìn và khả năng nhìn xa trông rộng, luôn biết cách định hướng và đưa ra quyết định trong những tình huống khó khăn. Sự tự tin trong cách làm việc, cùng với kỹ năng truyền cảm hứng tự nhiên, giúp họ có thể dẫn dắt một nhóm người tiến lên và đạt được mục tiêu chung. Điều này khiến họ không chỉ là một nhà lãnh đạo mà còn là người bạn đồng hành đáng tin cậy, sẵn sàng chia sẻ kiến thức và kinh nghiệm để giúp đỡ người khác.\n'+
      'Tuy nhiên, vì quá tự tin và đặt ra tiêu chuẩn cao, người mang chỉ số sứ mệnh 1 đôi khi thiếu kiên nhẫn với những người không làm theo mong muốn của mình. Họ có thể trở nên cứng nhắc, thậm chí là hách dịch khi cảm thấy không được hỗ trợ hay hợp tác như mong đợi. Điều này có thể khiến họ tạo ra khoảng cách với đồng nghiệp hoặc bạn bè, dễ dẫn đến tình huống không thoải mái trong giao tiếp và làm việc. Để phát huy hết tiềm năng của mình, những người mang chỉ số này cần học cách kiên nhẫn, lắng nghe và thấu hiểu người khác nhiều hơn, để tạo dựng các mối quan hệ bền vững và xây dựng môi trường làm việc hài hòa.\n'+
      'Về mặt nghề nghiệp, người có chỉ số sứ mệnh 1 phù hợp với những công việc cho phép họ phát huy tính sáng tạo, khả năng lãnh đạo và tinh thần tiên phong. Các lĩnh vực như doanh nhân, quản lý cấp cao, chính trị gia hay nhà lãnh đạo doanh nghiệp thường là môi trường lý tưởng cho họ phát triển. Nhờ vào tài năng và cá tính mạnh mẽ, họ dễ dàng gây dựng sự nghiệp thành công và tạo ra những giá trị to lớn, không chỉ cho bản thân mà còn cho cộng đồng xung quanh.\n',
      2: 'Chỉ số sứ mệnh của bạn là: 2\n' +
      'Những người mang chỉ số sứ mệnh số 2 trong thần số học là hiện thân của sự nhạy cảm, tinh tế và khả năng giao tiếp tuyệt vời. Họ biết lắng nghe, thấu hiểu và luôn tìm cách duy trì sự hài hòa trong các mối quan hệ. Nhờ vào tính cách nhẹ nhàng và khả năng đồng cảm, những người này dễ dàng trở thành trung tâm sự chú ý, vì họ luôn mang đến cảm giác an toàn và thoải mái cho người xung quanh. Họ là người đồng hành đáng tin cậy, luôn ủng hộ và sẵn lòng giúp đỡ những người thân yêu trong mọi hoàn cảnh.\n' +
      'Người mang chỉ số sứ mệnh 2 không chỉ kiên nhẫn mà còn rất bình tĩnh, có khả năng xử lý các tình huống một cách khéo léo. Họ thường đặt lợi ích của người khác lên trên bản thân, và điều này giúp họ xây dựng mối quan hệ tốt đẹp và lâu dài. Sự nhạy cảm tự nhiên giúp họ dễ dàng nhận biết những biến động nhỏ nhất trong tâm trạng và cảm xúc của người khác, từ đó tạo ra sự gắn kết sâu sắc và tin cậy. Đặc biệt, họ có khả năng làm dịu xung đột và giải quyết bất đồng một cách ôn hòa.\n'+
      'Bên cạnh đó, sự khéo léo trong giao tiếp và khả năng thuyết phục bẩm sinh cũng là những điểm mạnh nổi bật của người mang chỉ số sứ mệnh 2. Họ biết cách lựa chọn ngôn từ để truyền đạt ý kiến của mình một cách rõ ràng, dễ hiểu và luôn mang tính xây dựng. Từ đó, họ dễ dàng gắn kết với mọi người, xây dựng mạng lưới xã hội vững mạnh và bảo vệ những người mình yêu quý. Tuy nhiên, mặt trái của sự nhạy cảm là họ có thể dễ dàng bị tổn thương và thiếu tự tin khi phải đối mặt với những quyết định quan trọng. Đôi khi, sự nhạy cảm quá mức có thể khiến họ trở nên bị động, kéo dài nỗi buồn hoặc thậm chí tránh né trách nhiệm.\n'+
      'Về mặt nghề nghiệp, người có chỉ số sứ mệnh 2 phù hợp với các công việc đòi hỏi sự nhạy bén và khéo léo trong giao tiếp, như nhà ngoại giao, cố vấn tâm lý, giáo viên, bán hàng hoặc công tác xã hội. Trong các vai trò này, họ có thể phát huy tối đa khả năng thấu hiểu và mang lại những giá trị tích cực cho cộng đồng.\n',
      3: 'Chỉ số sứ mệnh của bạn là: 3\n' +
      'Trong thần số học, chỉ số sứ mệnh 3 là biểu tượng của sự sáng tạo, lạc quan và nhiệt huyết. Người mang số sứ mệnh này có khả năng sáng tạo vượt trội, luôn tìm ra những giải pháp mới mẻ và độc đáo cho các vấn đề trong công việc và cuộc sống. Họ là những người yêu nghệ thuật và luôn mang lại niềm vui cho mọi người xung quanh. Với họ, cuộc sống không chỉ là sự thành công về mặt vật chất mà còn là hành trình khám phá và trải nghiệm đầy màu sắc.\n'+
      'Sự lạc quan và tính cách vui vẻ là những đặc điểm nổi bật của người mang chỉ số sứ mệnh 3. Họ luôn nhìn mọi thứ bằng ánh mắt tích cực, dễ dàng vượt qua những nỗi đau và thất bại, từ đó tiếp tục vươn lên và tận hưởng cuộc sống. Điều này khiến họ trở thành những người bạn lý tưởng, dễ dàng tạo niềm vui và lan tỏa năng lượng tích cực đến mọi người. Ngoài ra, họ còn sở hữu sự hài hước và niềm đam mê với những công việc họ theo đuổi, khiến họ luôn nổi bật và thu hút sự chú ý.\n'+
      'Tuy nhiên, với cá tính phóng khoáng và tư duy sáng tạo mạnh mẽ, người mang chỉ số sứ mệnh 3 đôi khi gặp khó khăn trong việc duy trì sự tập trung và kiên trì. Họ có xu hướng dễ mất tập trung, dễ bị ảnh hưởng bởi cảm xúc và có thể đưa ra những quyết định vội vàng. Để phát huy tối đa tiềm năng, họ cần học cách kiểm soát cảm xúc và duy trì sự tập trung vào mục tiêu dài hạn.\n'+
      'Về nghề nghiệp, người sở hữu chỉ số sứ mệnh 3 thường phù hợp với những công việc liên quan đến nghệ thuật và sáng tạo như diễn viên, nhạc sĩ, nhà thiết kế, hoặc công tác giảng dạy. Nhờ vào sự lạc quan và khả năng truyền cảm hứng, họ dễ dàng thành công và mang lại giá trị cho cộng đồng thông qua tài năng của mình.',
      4: 'Chỉ số sứ mệnh của bạn là: 4\n' +
      'Những người mang chỉ số sứ mệnh 4 được biết đến với tính cách đáng tin cậy, kỷ luật và có tổ chức. Họ là những người thực tế và luôn giữ vững lập trường trong mọi tình huống. Với tính cách ổn định và bền bỉ, người mang chỉ số này thường là chỗ dựa vững chắc cho gia đình và bạn bè. Họ luôn có kế hoạch rõ ràng và tổ chức cuộc sống một cách hệ thống, giúp họ dễ dàng đạt được những thành tựu thực tế và cảm thấy hài lòng với cuộc sống.\n' +
      'Người mang chỉ số sứ mệnh 4 có khả năng phân chia công việc hợp lý, làm việc chăm chỉ và tuân thủ kỷ luật. Sự bình tĩnh và khả năng kiểm soát cảm xúc giúp họ trở thành người đáng tin cậy trong mọi hoàn cảnh. Tuy nhiên, tính cách kiên định đôi khi khiến họ trở nên cứng nhắc và khó linh hoạt trước những thay đổi. Họ thường có xu hướng kiểm soát, không thích bị can thiệp và luôn muốn tự mình quản lý mọi việc, đặc biệt là trong cuộc sống gia đình.n' +
      'Điểm yếu của người mang chỉ số sứ mệnh 4 là dễ bị cuốn vào công việc, đôi khi đến mức tham công tiếc việc, khó cân bằng thời gian cho bản thân. Họ có thể trở nên cứng đầu và thiếu linh hoạt, dẫn đến mâu thuẫn với những người xung quanh. Để giảm bớt áp lực và căng thẳng, họ cần học cách thả lỏng, thư giãn và dành thời gian cho các hoạt động giải trí.\n' +
      'Về mặt nghề nghiệp, người mang chỉ số sứ mệnh 4 thường phù hợp với các công việc liên quan đến quản lý, kế toán, xây dựng, hoặc công việc đòi hỏi tính kỷ luật và sự ổn định cao. Trong những môi trường này, họ có thể phát huy tối đa thế mạnh của mình và xây dựng sự nghiệp bền vững.\n',
      5:'Chỉ số sứ mệnh của bạn là: 5\n' +
      'Người mang chỉ số sứ mệnh số 5 là những người yêu thích sự tự do, mạo hiểm và luôn khao khát trải nghiệm mới mẻ. Họ có cá tính mạnh mẽ, thích phiêu lưu và không ngừng tìm kiếm sự đa dạng trong cuộc sống. Với họ, cuộc sống phải tràn đầy hứng khởi, thử thách và không bị ràng buộc. Chính sự năng động và sáng tạo giúp họ dễ dàng thích nghi với những thay đổi và đạt được thành công trong môi trường linh hoạt.\n' +
      'Người mang chỉ số sứ mệnh 5 thường có khả năng giao tiếp xuất sắc, dễ dàng kết nối và tạo dựng mối quan hệ mới. Họ không thích gò bó trong môi trường văn phòng mà thường hướng đến các công việc có tính linh hoạt cao. Những công việc liên quan đến tiếp thị, quảng cáo, nhà văn hoặc nhà báo là lựa chọn lý tưởng để họ phát huy khả năng và tinh thần tự do của mình. Với tính cách thẳng thắn, tháo vát, người mang chỉ số 5 thường là người tạo ra bầu không khí sôi động và dễ dàng trở thành trung tâm của sự chú ý.\n' +
      'Tuy nhiên, vì đam mê tự do, họ có xu hướng hành động theo cảm hứng và dễ đưa ra quyết định vội vàng. Điều này có thể dẫn đến hậu quả không mong muốn nếu họ không suy nghĩ kỹ lưỡng. Để tránh những sai lầm, họ cần học cách kiểm soát cảm xúc và cẩn trọng hơn trong các quyết định quan trọng.\n' +
      'Trên con đường sự nghiệp, họ thường gặp những thách thức và thay đổi, nhưng nhờ vào tính linh hoạt và tinh thần lạc quan, người mang chỉ số sứ mệnh 5 có thể học hỏi từ thất bại, nhanh chóng thích nghi và đạt được những thành công đáng kể.\n',
      6:'Chỉ số sứ mệnh của bạn là: 6\n' +
      'Người mang chỉ số sứ mệnh 6 thường được biết đến là những người giàu tình cảm, luôn hướng đến sự hoàn hảo và chu toàn. Với họ, gia đình và các mối quan hệ thân thiết là điều quan trọng nhất. Từ khi còn nhỏ, họ đã được giáo dục trong tinh thần trách nhiệm và tình yêu thương, khiến họ luôn sẵn lòng giúp đỡ và chăm sóc người khác.\n'+
      'Người mang chỉ số sứ mệnh 6 có khả năng phán đoán tốt, suy nghĩ chín chắn và biết cách đánh giá tính cách của người khác. Họ có xu hướng lan tỏa tình yêu thương, luôn tìm kiếm sự hài hòa và mong muốn mang đến điều tốt đẹp cho cộng đồng. Dù vậy, do luôn muốn mang lại sự hài hòa và hạnh phúc cho mọi người, người mang chỉ số sứ mệnh 6 đôi khi đặt quá nhiều áp lực lên bản thân. Họ có xu hướng hoàn hảo hóa mọi thứ và dễ bị căng thẳng khi không đạt được những tiêu chuẩn đã đề ra. Sự nhạy cảm này khiến họ dễ bị tổn thương khi bị người khác hiểu lầm hoặc phán xét.\n'+
      'Về mặt tình cảm, người mang chỉ số sứ mệnh 6 thường là người bạn đời tận tâm và luôn biết cách giữ lửa trong mối quan hệ. Họ trung thành, biết chăm sóc và rất tận tụy với người thân. Tuy nhiên, họ cần học cách thả lỏng và chấp nhận rằng không phải lúc nào mọi thứ cũng hoàn hảo như mong muốn. Sự cởi mở và linh hoạt sẽ giúp họ cảm thấy dễ chịu và cân bằng hơn trong cuộc sống.\n'+
      'Trong công việc, những người mang chỉ số sứ mệnh 6 thường phù hợp với các vai trò đòi hỏi tính tỉ mỉ và chăm sóc người khác, như giáo viên, y tá, nhà tư vấn hoặc công tác từ thiện. Những công việc này giúp họ phát huy sự tận tâm và tạo ra tác động tích cực đến cộng đồng. Người mang chỉ số 6 có khả năng dẫn dắt và truyền cảm hứng mạnh mẽ, tạo nên không gian an lành cho người xung quanh.\n',
      7:'Chỉ số sứ mệnh của bạn là: 7\n' +
      'Người mang chỉ số sứ mệnh 7 là những người sâu sắc, hướng nội và thích khám phá những ý nghĩa sâu xa của cuộc sống. Họ có xu hướng suy tư và tìm kiếm những kiến thức mới mẻ để hiểu rõ bản thân và thế giới xung quanh. Với khả năng quan sát tinh tế, người mang số sứ mệnh này thường là người thích nghiên cứu và có khả năng suy luận logic tốt.\n' +
      'Tuy nhiên, vì tính cách hướng nội và thích ở một mình, người mang chỉ số sứ mệnh 7 thường gặp khó khăn trong việc mở lòng với người khác. Họ dễ dàng cảm thấy mệt mỏi khi phải giao tiếp xã hội và đôi khi bị hiểu lầm là khó gần. Người mang số sứ mệnh này có xu hướng sống nội tâm, thích nghiêm túc và cẩn trọng trong mọi hành động.\n' +
      'Sự nghiệp của người mang chỉ số sứ mệnh 7 thường liên quan đến các lĩnh vực nghiên cứu, giảng dạy, hoặc các công việc đòi hỏi sự phân tích và đào sâu. Họ có thể trở thành nhà nghiên cứu, triết gia, hoặc nhà tư vấn tâm lý. Dù công việc có đòi hỏi độc lập và thời gian, người mang chỉ số này luôn tận tâm và có thể tạo ra những phát hiện giá trị.\n',
      8:'Chỉ số sứ mệnh của bạn là: 8\n' +
      'Người có chỉ số sứ mệnh số 8 trong thần số học thường là những cá nhân mạnh mẽ, quyết đoán và có tố chất lãnh đạo. Họ không ngại khó khăn và luôn hướng đến mục tiêu cao cả. Người mang số 8 có khả năng quản lý tốt tài chính và có ý chí kiên cường để đạt được sự thành công trong sự nghiệp.\n' +
      'Nhờ vào tính cách mạnh mẽ và sự quyết đoán, người mang chỉ số sứ mệnh 8 dễ dàng tạo dựng uy tín và lãnh đạo trong mọi lĩnh vực. Tuy nhiên, họ cần chú ý kiểm soát cảm xúc và tránh sự áp đặt đối với người khác. Sự tham vọng có thể khiến họ trở nên cứng nhắc và bỏ qua những giá trị tinh thần quan trọng trong cuộc sống.\n' +
      'Người có chỉ số sứ mệnh 8 phù hợp với các vai trò quản lý, doanh nhân hoặc các vị trí lãnh đạo trong lĩnh vực tài chính. Khả năng phân tích và xử lý thông tin giúp họ đưa ra quyết định đúng đắn và dễ dàng thành công trong môi trường cạnh tranh.\n',
      9:'Chỉ số sứ mệnh của bạn là: 9\n' +
      'Chỉ số sứ mệnh số 9 đại diện cho lòng nhân ái, từ bi và tình yêu thương. Người mang số 9 thường có lý tưởng cao đẹp, hướng đến việc giúp đỡ người khác và làm cho thế giới trở nên tốt đẹp hơn. Họ có tầm nhìn rộng lớn và luôn muốn mang lại giá trị cho cộng đồng thông qua những hành động nhân ái.\n' +
      'Người mang chỉ số sứ mệnh 9 luôn sẵn sàng hy sinh và cho đi mà không cần nhận lại. Họ rất dễ tha thứ và luôn cố gắng duy trì sự hòa hợp. Tuy nhiên, họ có thể bị lợi dụng nếu không biết bảo vệ bản thân. Đôi khi, sự vị tha quá mức có thể khiến họ bỏ qua nhu cầu cá nhân, dẫn đến cảm giác mệt mỏi và mất cân bằng.\n' +
      'Về mặt nghề nghiệp, người mang chỉ số sứ mệnh 9 phù hợp với các lĩnh vực nhân đạo, từ thiện, giảng dạy hoặc nghệ thuật. Họ có khả năng truyền cảm hứng mạnh mẽ và làm cho mọi người cảm thấy được yêu thương. Những người mang số sứ mệnh này sẽ tìm thấy sự thỏa mãn trong các công việc có ý nghĩa, giúp họ thể hiện lòng nhân ái và sự đồng cảm của mình đối với cộng đồng.\n',
      11: 'Chỉ số sứ mệnh của bạn là 11\n'+
      'Số sứ mệnh 11 là một trong những con số quyền năng và mang tính tâm linh cao nhất trong thần số học, đại diện cho sự trực giác mạnh mẽ, khả năng nhìn xa trông rộng và tiềm năng chữa lành tinh thần. Người mang số 11 thường có một chiều sâu tâm hồn lớn và khả năng cảm nhận được cảm xúc, suy nghĩ của người khác. Với trực giác phong phú, họ dễ dàng nhận ra những cơ hội mà người khác có thể bỏ qua, và thường mang lại sự bình yên, an ủi cho những ai cần đến.\n'+
      'Người có chỉ số sứ mệnh 11 thường được xem như “người truyền cảm hứng” bởi khả năng thấu hiểu và truyền đạt của mình. Họ dễ dàng tạo được sự tin tưởng và luôn mong muốn lan tỏa thông điệp tích cực đến cộng đồng. Tuy nhiên, họ cũng có thể cảm thấy áp lực khi mang trên vai những trọng trách lớn, đôi khi cảm thấy không hiểu chính mình và dễ bị tổn thương vì nhạy cảm trước những tác động bên ngoài.\n'+
      'Trong sự nghiệp, người có số sứ mệnh 11 phù hợp với những lĩnh vực đòi hỏi sự sáng tạo và khả năng kết nối như nghệ thuật, tư vấn tâm lý, hoặc các hoạt động từ thiện. Với trí tưởng tượng phong phú, họ có thể trở thành nhà lãnh đạo đầy cảm hứng, giúp người khác nhận ra giá trị của bản thân.\n',
      22: 'Chỉ số sứ mệnh của bạn là 22\n'+
      'Chỉ số sứ mệnh số 22 được coi là một trong những con số đặc biệt nhất trong thần số học, kết hợp giữa khả năng tư duy logic của số 4 và chiều sâu tâm linh của số 11. Người mang số 22 thường sở hữu những khả năng phi thường, có khả năng biến những ý tưởng lớn lao thành hiện thực. Họ là những người có cái nhìn thực tế nhưng không kém phần giàu trí tưởng tượng và sáng tạo.\n'+
      'Người mang số 22 thường đặt ra những mục tiêu cao cả và không ngừng nỗ lực để đạt được chúng. Họ có khả năng tổ chức, hoạch định vượt trội, luôn sẵn sàng đối mặt với thử thách và không ngại hy sinh cho lý tưởng. Tuy nhiên, nếu không biết kiểm soát, tham vọng có thể trở thành áp lực khiến họ cảm thấy căng thẳng và mất đi sự cân bằng trong cuộc sống.\n'+
      'Về sự nghiệp, người sở hữu chỉ số sứ mệnh 22 phù hợp với các vai trò lãnh đạo trong các lĩnh vực liên quan đến xây dựng, phát triển cộng đồng, hoặc các ngành nghề đòi hỏi tầm nhìn dài hạn và khả năng quản lý tốt. Những công việc này cho phép họ tận dụng tối đa tiềm năng và tạo ra những giá trị lớn lao, góp phần thay đổi xã hội.\n',
      33: 'Chỉ số sứ mệnh của bạn là 33\n'+
      'Số sứ mệnh 33 được gọi là “con số của sự hy sinh”, biểu hiện cho tình yêu vô điều kiện, lòng nhân ái và lòng vị tha. Người mang số 33 thường là người có trách nhiệm cao trong việc giúp đỡ và chăm sóc người khác. Họ là những người nhạy cảm, sẵn sàng hy sinh lợi ích cá nhân vì cộng đồng và có thể trở thành những người truyền cảm hứng cho những giá trị tốt đẹp.\n'+
      'Người có số 33 trong chỉ số sứ mệnh có thể mang đến sự chữa lành, giúp xoa dịu nỗi đau và đem lại niềm vui cho những ai gặp khó khăn. Tuy nhiên, vì dành quá nhiều thời gian và công sức cho người khác, đôi khi họ bỏ quên bản thân và có thể dẫn đến cảm giác mệt mỏi, kiệt sức. Điều quan trọng là người mang số 33 cần học cách giữ sự cân bằng, biết khi nào nên giúp đỡ và khi nào cần chăm sóc chính mình.\n'+
      'Trong công việc, số sứ mệnh 33 phù hợp với các nghề nghiệp liên quan đến sự hỗ trợ và cống hiến như y học, giáo dục, công tác xã hội, hoặc các tổ chức từ thiện. Những lĩnh vực này giúp họ phát huy lòng trắc ẩn và làm cho cuộc sống của người khác trở nên tốt đẹp hơn, điều đó mang lại sự thỏa mãn và cảm giác thành tựu sâu sắc cho họ.\n',
  }

export default ChiSoSuMenh
