const SoNangLucNgaySinh = {
    1:'Chỉ số ngày sinh của bạn là: 1\n' +
    'Những người sinh vào ngày có chỉ số 1 thường sở hữu tinh thần độc lập cao và luôn khao khát làm việc một cách tự chủ, tự do. Đối với họ, không gian riêng là một yếu tố vô cùng quan trọng, giúp họ phát triển toàn diện và bộc lộ rõ bản chất độc đáo của mình. Trong cuộc sống, Con số chủ đạo đóng vai trò như kim chỉ nam, định hướng con người này theo những giá trị, mục tiêu phù hợp với năng lượng cá nhân. Tuy nhiên, với tính cách mạnh mẽ và mong muốn tự quyết, người mang Chỉ số Ngày sinh 1 dễ bị cuốn vào tham vọng cá nhân và rời xa con đường mà Con số chủ đạo vạch ra. Họ thường thích tập trung vào cá nhân, có xu hướng hoạt động đơn lẻ và thích tự mình hoàn thành mọi việc theo cách riêng. Vì thế, đôi khi họ có thể tỏ ra tách biệt trong môi trường tập thể, nhất là khi còn nhỏ. Điều này đặc biệt dễ thấy ở những trẻ sinh ngày đầu tháng, nhưng cha mẹ không nên lo lắng vì đó chỉ là dấu hiệu cho thấy các em đang học cách tận hưởng không gian riêng và phát triển bản thân một cách tự nhiên.\n',
    2:'Chỉ số ngày sinh của bạn là: 2\n' +
    'Người sinh vào ngày có Chỉ số Ngày sinh 2 mang trong mình năng lượng của sự nhạy cảm và trực giác. Với khả năng nhận biết tinh tế, họ thường có trực giác nhạy bén, giúp ích rất nhiều trong việc đưa ra các quyết định quan trọng. Họ cảm thấy thoải mái nhất khi được làm việc và hợp tác cùng những người có tính cách điềm tĩnh, lạc quan, và mang lại cảm giác bình yên. Những người này yêu thích những hình thức giải trí nhẹ nhàng, đặc biệt là hài kịch, bởi nó phù hợp với bản chất tinh tế của họ; thường họ thích ở vai trò khán giả hơn là người biểu diễn. Được biết đến với lòng đáng tin cậy, tính hữu dụng và sự nhiệt tình trong việc hỗ trợ người khác, họ dễ dàng xây dựng mối quan hệ bền vững, và luôn là điểm tựa tinh thần cho những người xung quanh. Nhìn chung, người có Chỉ số Ngày sinh 2 đề cao sự tự nhiên, không thích sự phức tạp hay giả tạo trong các mối quan hệ.\n',
    3:'Chỉ số ngày sinh của bạn là: 3\n' +
    'Trái với tính cách trầm lặng của người có Chỉ số Ngày sinh 2, người có Chỉ số Ngày sinh 3 lại có xu hướng hướng ngoại rõ ràng. Họ không chỉ thích mà còn chủ động đem lại niềm vui và tiếng cười cho mọi người xung quanh, dù là trong gia đình, tại nơi làm việc, hay trong những hoạt động cộng đồng. Năng lượng của họ thường sôi nổi, vui tươi, khiến cho những người này trở thành tâm điểm của các buổi tụ họp, sự kiện. Vì có nhiều sở thích và chí hướng lớn, họ thường thích hợp với công việc dự án hoặc bán thời gian, giúp họ có thêm thời gian theo đuổi các đam mê cá nhân. Những người này rất yêu thích hài hước, đặc biệt là hài châm biếm, và thường sử dụng nó như một công cụ để kết nối với mọi người xung quanh. Tuy nhiên, vì tính cách thông minh và nhanh nhạy, họ có thể có xu hướng chỉ trích người khác, nhất là với những người chậm rãi hơn mình. Để tránh điều này, họ nên phát huy sự hài hước nhẹ nhàng nhằm “chỉ điểm” khéo léo cho người khác những gì cần điều chỉnh, thay vì chỉ trích trực tiếp, tránh gây ra xung đột không đáng có.\n',
    4:'Chỉ số ngày sinh của bạn là: 4\n' +
    'Những người có Chỉ số Ngày sinh 4 là những người mang năng lượng của tính thực tế và sự kiên trì. Họ có xu hướng diễn đạt bản thân qua các kỹ năng thực tiễn, khéo léo của đôi bàn tay, chẳng hạn như làm đồ thủ công, nhảy múa, hoặc các môn thể thao. Nếu Con số chủ đạo của họ là số lẻ, Chỉ số Ngày sinh 4 sẽ giúp họ phát triển thêm các khía cạnh sáng tạo và nghệ thuật trong cuộc sống. Ngược lại, nếu Con số chủ đạo là số chẵn, những người này có thể dễ bị cuốn vào sự quyến rũ của vật chất, và vì thế, cần luôn nhắc nhở bản thân không để điều này lấn át các giá trị tinh thần. Bản chất kiên nhẫn của họ là một điểm mạnh quý giá, giúp họ đạt được thành công bền vững, miễn là họ không bỏ cuộc và luôn duy trì nỗ lực trong mọi hoàn cảnh.\n',
    5:'Chỉ số ngày sinh của bạn là: 5\n' +
    'Người có Chỉ số Ngày sinh 5 là những cá nhân giàu cảm xúc và có lòng nhân ái lớn lao. Họ luôn sẵn lòng chăm sóc, quan tâm và giúp đỡ người khác, vì đối với họ, sự tự do biểu đạt cảm xúc là một nhu cầu thiết yếu. Người có Chỉ số Ngày sinh 5 cũng rất nhạy cảm, nhưng nhờ sự cân bằng trong bản thân, họ vẫn có khả năng đạt được thành công và hạnh phúc trong cuộc sống, miễn là họ không để nỗi sợ bị hiểu lầm cản trở. Nếu vì e ngại mà họ ngại ngùng, tự thu mình, thì điều này sẽ cản trở khả năng biểu đạt cảm xúc tự nhiên. Vì vậy, người có Chỉ số Ngày sinh 5 nên tham gia các hoạt động ngoài trời, chọn bạn bè là những người vui vẻ, hoạt bát để bổ sung năng lượng tích cực, từ đó sống cởi mở và tận hưởng niềm vui cuộc sống một cách trọn vẹn\n',
    6:'Chỉ số ngày sinh của bạn là: 6\n' +
    'Số 6 thường mang ý nghĩa sáng tạo, nhưng người có Chỉ số Ngày sinh 6 thường giới hạn sự sáng tạo này trong gia đình. Đặc biệt, phụ nữ có Chỉ số Ngày sinh 6 thường có xu hướng dành phần lớn thời gian chăm lo cho gia đình hơn là tham gia các hoạt động bên ngoài. Tuy nhiên, nhờ tình yêu thương và niềm đam mê cái đẹp, người sinh ngày này thường có khả năng làm sáng bừng cả ngôi nhà, giúp gia đình trở nên ấm áp, vui vẻ. Nếu không giữ tinh thần tích cực, những người này dễ rơi vào lo âu, thường suy nghĩ nhiều về những vấn đề nhỏ nhặt trong gia đình, thậm chí “chuyện bé xé ra to”. Để tránh điều này, họ nên tìm kiếm các sở thích sáng tạo như vẽ, làm đồ thủ công, hoặc âm nhạc để duy trì năng lượng tích cực và cân bằng cuộc sống.\n',
    7:'Chỉ số ngày sinh của bạn là: 7\n' +
    'Những người mang Chỉ số Ngày sinh 7 thường học những bài học sâu sắc từ chính trải nghiệm của bản thân, và không ít lần là những bài học từ tổn thất và hy sinh. Những tổn thất này thường liên quan đến tài chính hơn là tình cảm hay sức khỏe. Nếu không học được bài học từ những tổn thất ban đầu, họ có thể sẽ phải đối mặt với những mất mát ở các lĩnh vực khác. Khi trưởng thành hơn về mặt trí tuệ, họ sẽ nhận ra thôi thúc chia sẻ kinh nghiệm sống của mình với người khác, thường qua vai trò người hướng dẫn hoặc cố vấn. Những trải nghiệm phong phú và sâu sắc này sẽ làm giàu thêm cho tâm hồn của họ, giúp họ cảm nhận rõ hơn về giá trị cuộc sống.\n',
    8:'Chỉ số ngày sinh của bạn là: 8\n' +
    'Người mang Chỉ số Ngày sinh 8 là những người đề cao sự độc lập, không chỉ trong tài chính mà còn trong tư tưởng và cảm xúc. Họ có xu hướng không thích làm việc nhóm vì điều này có thể làm cản trở quá trình phát triển cá nhân. Trong hành trình cuộc đời, họ sẽ dần nhận ra nhu cầu ngày càng lớn trong việc biểu đạt cảm xúc và trực giác một cách độc lập. Độc lập là nền tảng cho mọi biểu đạt của họ, nhưng đôi khi, người mang Chỉ số Ngày sinh 8 có thể hiểu nhầm rằng độc lập chỉ đồng nghĩa với độc lập tài chính. Họ cần hiểu rằng độc lập tài chính chỉ là một biểu hiện nhỏ trong sự tự do toàn diện. Nếu không nắm bắt đúng điều này, sự thành công về tài chính của họ có thể sẽ không bền vững.\n',
    9:'Chỉ số ngày sinh của bạn là: 9\n' +
    'Những người có Chỉ số Ngày sinh 9 mang trong mình trách nhiệm lớn đối với bản thân và cộng đồng, được thúc đẩy bởi lý tưởng và những giấc mơ cao cả. Đôi khi, họ trở nên nghiêm túc quá mức, điều này có thể khiến họ gặp căng thẳng và cần có bạn bè lạc quan, vui vẻ để giữ cân bằng. Nếu lý tưởng của họ không được định hướng tốt, họ dễ cảm thấy thất vọng và gặp rắc rối trong cuộc sống cá nhân. Họ cần tránh các cuộc cãi vã nghiêm trọng và học cách thể hiện quan điểm một cách nhẹ nhàng hơn.\n',
    10:'Chỉ số ngày sinh của bạn là: 10\n' +
    'Người có Chỉ số Ngày sinh 10 mang trong mình năng lượng của sự quyết tâm và mạnh mẽ. Họ có một ý chí kiên cường và khát khao thành công mãnh liệt, luôn nỗ lực không ngừng để đạt được mục tiêu của mình. Tuy nhiên, họ cần phải cân bằng giữa việc theo đuổi thành công và duy trì các mối quan hệ xung quanh. Sự kiên định của họ có thể dẫn đến xung đột nếu họ quá cứng đầu hoặc ép buộc người khác đi theo quan điểm của mình. Bởi vậy, họ nên học cách lắng nghe và tiếp thu ý kiến từ người khác để phát triển bản thân một cách hài hòa và tránh tạo áp lực cho những người xung quanh. Nếu biết tận dụng sức mạnh này một cách khôn ngoan, người có Chỉ số Ngày sinh 10 sẽ trở thành những người lãnh đạo tài ba, truyền cảm hứng cho mọi người.\n',

    11:'Chỉ số ngày sinh của bạn là: 11/2\n' +
    'Người có Chỉ số Ngày sinh 11 là những người mang trong mình năng lượng tâm linh mạnh mẽ và có khả năng thấu hiểu sâu sắc về cuộc sống. Họ thường có khả năng nhận biết và cảm nhận được những điều mà người khác không dễ nhận thấy, và điều này khiến họ trở nên nhạy bén và tinh tế. Tuy nhiên, họ có thể dễ bị ảnh hưởng bởi năng lượng xung quanh, vì vậy họ cần học cách bảo vệ bản thân khỏi những tác động tiêu cực. Người có Chỉ số Ngày sinh 11 thường phù hợp với các lĩnh vực như nghệ thuật, tâm lý học, hoặc các công việc giúp đỡ người khác, nơi mà họ có thể tận dụng khả năng nhạy bén của mình. Nếu phát triển đúng hướng, họ có thể trở thành những nhà lãnh đạo tinh thần, giúp đỡ và truyền cảm hứng cho người khác.\n',
    22: 'Chỉ số ngày sinh của bạn là: 22/4\n' +
        'Con số ngày sinh 22/4 mang trong mình sức mạnh và tiềm năng vượt trội mà không phải ai cũng dễ dàng chạm đến. Đây là con số kết hợp hài hòa giữa trực giác nhạy bén và óc thực tế vững chắc, giúp người sở hữu có khả năng biến ước mơ thành hiện thực, miễn là họ thực sự quyết tâm và kiên trì. Với nền tảng sức mạnh của số 22 – một trong những “số bậc thầy” hiếm hoi trong thần số học – người mang chỉ số ngày sinh này có thể kiến tạo những điều lớn lao, để lại dấu ấn sâu sắc trong cuộc đời.\n' +
        'Tuy nhiên, để khai thác triệt để tiềm năng to lớn ấy, họ cần đạt được sự hòa hợp toàn diện giữa ba yếu tố: Thể chất, Tinh thần và Trí não. Chỉ khi ba yếu tố này cân bằng và hỗ trợ lẫn nhau, sức mạnh từ 22 mới có thể tỏa sáng và dẫn dắt họ đến thành công viên mãn. Ngược lại, nếu họ chỉ tập trung phát triển một khía cạnh mà bỏ quên những yếu tố còn lại, sức mạnh này có thể trở thành một công cụ bị lạm dụng, thúc đẩy bởi tham vọng kiểm soát hoặc thao túng.\n' +
        'Những người này nhạy cảm, trực giác cao và sức mạnh về tâm linh mà họ được ban tặng rất mạnh mẽ và gấp đôi số 11. Bên cạnh đó, họ lại vẫn có được tính thực tế của số 4.\n' +
        'Khi để tham vọng lấn át sự cân bằng nội tâm, họ có thể sẽ đánh mất nguồn năng lượng quý giá và lãng phí những nguồn lực bản thân. Những thất bại, tổn thương về mặt tinh thần hoặc thể chất, và sự đổ vỡ trong các mối quan hệ sẽ là những lời nhắc nhở cay đắng rằng con số ngày sinh chỉ là yếu tố phụ trợ, không phải là cứu cánh hay mục tiêu tối thượng. Cuộc sống của họ cần được xây dựng trên nền tảng của chỉ số chủ đạo – con số định hình bản ngã và mục đích cốt lõi trong hành trình cuộc đời – thay vì đặt toàn bộ trọng tâm vào sức mạnh thuần túy của ngày sinh.\n' +
        'Chỉ số ngày sinh 22/4 là một món quà đặc biệt nhưng cũng là một thử thách lớn. Để thành công, người sở hữu nó phải học cách lắng nghe chính mình, không ngừng rèn luyện, hoàn thiện, và quan trọng hơn hết, là giữ vững sự hài hòa giữa ba yếu tố cốt lõi để sức mạnh này trở thành một công cụ phục vụ cuộc sống ý nghĩa và trọn vẹn.\n'
}


export default SoNangLucNgaySinh
